language: python
python:
    - "2.7"
    - "pypy"
cache:
    apt: true
    directories:
    - $HOME/virtualenv/python2.7/lib/python2.7/site-packages
    - $HOME/virtualenv/pypy/site-packages
install:
    - pip install -r requirements/test.txt
script:
    - nosetests --with-cov --cov-report xml .
    - bash <(curl https://codecov.io/bash)
